FROM registry.redhat.io/ubi9-minimal

RUN microdnf -y install tar gzip

COPY software/grafana-10.0.0.linux-amd64.tar.gz /opt/

WORKDIR /opt

RUN tar -xzf grafana-10.0.0.linux-amd64.tar.gz

WORKDIR /opt/grafana-10.0.0

ENTRYPOINT [ "/opt/grafana-10.0.0/bin/grafana-server" ]
