{
 "title": "Kafka",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "K1 - Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{instance=\"k1:7000\"}",
     "legendFormat": "K1"
    }
   ]
  },
  {
   "title": "K1 - Heap Maximum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_max{instance=\"k1:7000\"}",
     "legendFormat": "K1"
    }
   ]
  },
  {
   "title": "K1 - Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_server_socket_server_metrics_request_total{instance=\"k1:7000\", networkProcessor=\"0\"}"
    },
    {
     "expr": "kafka_server_socket_server_metrics_request_total{instance=\"k1:7000\", networkProcessor=\"1\"}"
    },
    {
     "expr": "kafka_server_socket_server_metrics_request_total{instance=\"k1:7000\", networkProcessor=\"2\"}"
    }
   ]
  },
  {
   "title": "K1 - Total Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kafka_server_socket_server_metrics_response_total{instance=\"k1:7000\", networkProcessor=\"0\"}"
    },
    {
     "expr": "kafka_server_socket_server_metrics_response_total{instance=\"k1:7000\", networkProcessor=\"1\"}"
    },
    {
     "expr": "kafka_server_socket_server_metrics_response_total{instance=\"k1:7000\", networkProcessor=\"2\"}"
    }
   ]
  },
  {
   "title": "K2 - Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{instance=\"k2:7000\"}",
     "legendFormat": "K2"
    }
   ]
  },
  {
   "title": "K2 - Heap Maximum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_max{instance=\"k2:7000\"}",
     "legendFormat": "K2"
    }
   ]
  },
  {
   "title": "K2 - Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kafka_server_socket_server_metrics_request_total{instance=\"k2:7000\", networkProcessor=\"0\"}"
    },
    {
     "expr": "kafka_server_socket_server_metrics_request_total{instance=\"k2:7000\", networkProcessor=\"1\"}"
    },
    {
     "expr": "kafka_server_socket_server_metrics_request_total{instance=\"k2:7000\", networkProcessor=\"2\"}"
    }
   ]
  },
  {
   "title": "K2 - Total Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "kafka_server_socket_server_metrics_response_total{instance=\"k2:7000\", networkProcessor=\"0\"}"
    },
    {
     "expr": "kafka_server_socket_server_metrics_response_total{instance=\"k2:7000\", networkProcessor=\"1\"}"
    },
    {
     "expr": "kafka_server_socket_server_metrics_response_total{instance=\"k2:7000\", networkProcessor=\"2\"}"
    }
   ]
  }
 ]
}