global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 'localhost:9090'
  - job_name: zookeeper
    static_configs:
      - targets:
          - 'zk1:7000'
          - 'zk2:7000'
          - 'zk3:7000'
  - job_name: kafka
    static_configs:
      - targets:
          - 'k1:7000'
          - 'k2:7000'
          - 'k3:7000'
